FROM node:20-slim AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

FROM node:20-slim AS production

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app /usr/src/app

RUN useradd --user-group --create-home --shell /bin/false appuser

RUN chown -R appuser:appuser /usr/src/app

COPY ./start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

USER appuser

ENV NODE_ENV=production
EXPOSE 4001

ENTRYPOINT ["/usr/local/bin/start.sh"]


