apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiService }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      name: http-service
  type: ClusterIP