version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19
    working_directory: ~/repo

jobs:
  backend-test:
    docker:
      - image: cimg/node:18.19
      - image: mongo:6.0
        name: mongodb
        environment:
          MONGO_INITDB_DATABASE: testdb
    working_directory: ~/repo/Backend

    steps:
      - checkout

      - run:
          name: Set Mongo URI for CI
          command: echo 'export MONGO_URI="mongodb://mongodb:27017/testdb"' >> $BASH_ENV

      - run:
          name: Debug current directory
          command: |
            pwd
            ls -l
            ls -l Backend
            cat Backend/package.json

      - run:
          name: Install dependencies and run tests
          command: |
            cd Backend
            npm ci
            npm test


  build-and-push:
    docker:  
      - image: cimg/base:current
    resource_class: my-dev/medium
    steps:
      - checkout
      - run:
          name: Build backend image
          command: docker build -t $DOCKERHUB_USERNAME/e-commerce-project-backend:latest ./Backend
      - run:
          name: Build frontend image
          command: docker build -t $DOCKERHUB_USERNAME/e-commerce-project-frontend:latest ./Frontend
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push backend image
          command: docker push $DOCKERHUB_USERNAME/e-commerce-project-backend:latest
      - run:
          name: Push frontend image
          command: docker push $DOCKERHUB_USERNAME/e-commerce-project-frontend:latest

  deploy:
    docker:  
      - image: cimg/base:current
    resource_class: my-dev/medium
    steps:
      - checkout
      - run:
          name: Deploy with Helm to Minikube
          command: |
            kubectl config use-context minikube
            helm upgrade --install e-commerce-web-app ./e-commerce-project-chart \
              --set backend.image=$DOCKERHUB_USERNAME/e-commerce-project-backend:latest \
              --set frontend.image=$DOCKERHUB_USERNAME/e-commerce-project-frontend:latest

workflows:
  version: 2
  ci-cd-workflow:
    jobs:
      - backend-test
      - build-and-push:
          requires:
            - backend-test
      - deploy:
          requires:
            - build-and-push