version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19
    working_directory: ~/repo

jobs:
  backend-test:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Print the current working directory
          command: pwd
      - run:
          name: List the directories and files inside the current working directory
          command: ls -l
      - run: 
          name: Set the Backend directory as the current directory
          command: cd Backend
      - run:
          name: List the directories and files inside the Backend directory
          command: ls -l
      - run:
          name: Check the package.json file content
          command: cat package.json
      - run:
          name: Install dependencies
          command: npm install
      - run: 
          name: Check the scripts
          command: npm run
      - run:
          name: Install Jest tests and Run Jest tests
          command: |
            npm install --save-dev jest supertest
            npm test

  build-and-push:
    machine: true
    resource_class: my-dev/dev123
    steps:
      - checkout
      - run:
          name: Build backend image
          command: docker build -t $DOCKERHUB_USERNAME/e-commerce-project-backend:latest ./Backend
      - run:
          name: Build frontend image
          command: docker build -t $DOCKERHUB_USERNAME/e-commerce-project-frontend:latest ./Frontend
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push backend image
          command: docker push $DOCKERHUB_USERNAME/e-commerce-project-backend:latest
      - run:
          name: Push frontend image
          command: docker push $DOCKERHUB_USERNAME/e-commerce-project-frontend:latest

  deploy:
    machine: true
    resource_class: my-dev/dev123
    steps:
      - checkout
      - run:
          name: Deploy with Helm to Minikube
          command: |
            kubectl config use-context minikube
            helm upgrade --install e-commerce-web-app ./e-commerce-project-chart \
              --set backend.image=$DOCKERHUB_USERNAME/e-commerce-project-backend:latest \
              --set frontend.image=$DOCKERHUB_USERNAME/e-commerce-project-frontend:latest

workflows:
  version: 2
  ci-cd-workflow:
    jobs:
      - backend-test
      - build-and-push:
          requires:
            - backend-test
      - deploy:
          requires:
            - build-and-push
