version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.0
  aws-ecr: circleci/aws-ecr@9.7.0
  terraform: circleci/terraform@3.7.0
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3.1
  node: circleci/node@5.1.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19
    working_directory: ~/repo

jobs:
  backend-test:
    docker:
      - image: cimg/node:18.19
      - image: mongo:6.0
        name: mongodb
        environment:
          MONGO_INITDB_DATABASE: testdb
    working_directory: ~/repo/Backend
    steps:
      - checkout
      - run:
          name: Set Mongo URI
          command: echo 'export MONGO_URI="mongodb://mongodb:27017/testdb"' >> $BASH_ENV
      - run:
          name: Install & Run Tests
          command: |
            npm ci
            npm test

  terraform-validate-plan:
    docker:
      - image: hashicorp/terraform:1.9
    working_directory: ~/repo/terraform
    steps:
      - checkout
      - aws-cli/setup
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .


  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.9
    working_directory: ~/repo/terraform
    steps:
      - checkout
      - aws-cli/setup
      - terraform/init:
          path: .
      - terraform/apply:
          path: .
          var: |
            aws_region=${AWS_REGION}

  build_and_push_image:
    executor: node-executor
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Get secrets manager credentials
          command: |
            aws secretsmanager get-secret-value --secret-id e-commmerce-app-production-credentials-v1 --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env
          path: ./Backend
      - aws-ecr/build_and_push_image:
          repo: e-commerce-proj-repo
          tag: latest
          path: ./Backend
          dockerfile: Dockerfile.prod

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - kubernetes/install-kubectl
      - helm/install-helm
      - run:
          name: Configure kubectl for EKS
          command: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy the usable charts
          command: |
            chmod +x ./e-commerce-project-chart/helm.sh
            ./e-commerce-project-chart/helm.sh
      - helm/upgrade:
          chart-path: ./e-commerce-project-chart
          release-name: e-commerce-web-app
          install: true

workflows:
  version: 2
  ci-cd-workflow:
    jobs:
      - backend-test
      - terraform-validate-plan:
          requires:
            - backend-test
          context: terraform
      - terraform-apply:
          filters:
            branches:
              only: main
          requires:
            - terraform-validate-plan
          context: terraform
      - build_and_push_image:
          requires:
            - terraform-apply
          context: terraform
      - deploy:
          requires:
            - build-and-push-backend
          context: terraform
